### ISSUE TITLE
Starting muted

### ISSUE THREAD

**Issue by jasonjenssen** [p-fruck/jim#28]
Hello!

Thanks for this amazing project. Is it possible to add that he unmutes as soon as a track starts? I got enabled that everyone starts muted.

Also, is a possibility planned to let him join from the browser?

Thanks, I really love it!

**Comment by p-fruck** [comment]
Hi,

thanks for the positive feedback and for reporting the issue :smile: 
The issue will be fixed in JIM v2.1.3 (will be created within the next hour), you can already try the development branch if you want ;)

> Also, is a possibility planned to let him join from the browser?

I'm sorry, but  don't get the question. JIM is a program, that automates a whole webbrowser to act like a real user.

Kind regards
Philipp
